version: '3.8'

services:
  web:
    build: .
    ports:
      - "3001:3001"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:paris12ysolo12@localhost:5432/api
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
